version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: nlw_heat_backend_node
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/home/node/app
    links:
      - db
    depends_on: 
      - db
  
  db:
    image: postgres
    restart: always
    container_name: nlw_heat_database_pg
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
    
  
